FROM python:3.13-alpine

# Variables de entorno
ENV PYTHONDONTWRITEBYTECODE=1
ENV PYTHONUNBUFFERED=1

# Directorio de trabajo
WORKDIR /app

# Instalar dependencias del sistema
RUN apk add --no-cache \
    gcc \
    musl-dev \
    mariadb-connector-c-dev \
    libffi-dev \
    build-base \
    linux-headers \
    bash

# Copiar e instalar dependencias
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

# Copiar el código del backend
COPY . .

# Copiar script para esperar a MySQL (desde la raíz)
COPY ./wait-for-db.sh .
RUN chmod +x wait-for-db.sh

# Exponer puerto
EXPOSE 8000

# Comando para desarrollo
CMD ["./wait-for-db.sh", "python", "manage.py", "runserver", "0.0.0.0:8000"]